<div class="panel panel-default">
    <div class="panel-body">
        <div class="pull-left">
            <div class="btn-group">
                <a href="<?php echo $this->linkToRoute('admin-users-create');?>" class="btn btn-success"><i class="fa fa-plus-circle"></i> Write new post</a>
            </div>
        </div>
        <div class="clearfix"></div>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
<?php
foreach ($this->list as $user) {

//    $publishStatusIcon = ($post->getStatus() ? "fa-check" : "fa-times");
//    $publishStatusColor = ($post->getStatus() ? "text-success" : "text-danger");
?>
                <tr>
                    <td><?php echo $user->getName();?></td>
                    <td><?php echo $user->getEmail();?></td>
                    <td>
                        <a href="<?php echo $this->linkToRoute('admin-user-edit', array($user->getId()));?>">
                            <i class="fa fa-pencil"></i>
                        </a>
                    </td>
                </tr>
<?php
}
?>
            </tbody>
        </table>
    </div>
</div>
