<div class="container">
  <div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6">
<?php
if (isset($this->result['result'])) {
    echo '<div class="alert alert-info">';
    echo $this->result['result'];
    echo '</div>';
}
?>
      <form class="form" method="post">

        <div class="form-group">
          <label for="username">Name</label>
          <input type="text" name="name" id="name" class="form-control" required>
        </div>

        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" name="username" id="username" class="form-control" required>
        </div>

        <div class="form-group">
          <label for="username">Email</label>
          <input type="email" name="email" id="email" class="form-control" required>
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" id="password" class="form-control" required>
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-info">Register</button>
        </div>
      </form>
    </div>
    <div class="col-xs-3"></div>
  </div>
</div>